### ISSUE TITLE
自动预览功能相关建议

### ISSUE THREAD

**Issue by howmp** [hoyt-tian/vscode-gitbook-kit#4]
首先感谢作者提供如此强大的vscode插件，在使用过程遇到以下问题

1. 当从源代码管理点击*.md文档的时候，预期看到的是Working Tree的对比，实际上仍然会强制预览

1. 当预览的时候，焦点能否留在md源码件的标签页

1. 可否提供一些可供配置的选项，如关闭预览功能、焦点的配置 

1. 在资源管理器中中GITBOOK STRUCTURE目录页面，能否增加单击编辑,右键添加目录等

os:windows 10

vscode:1.20.0

插件版本:0.5.0

**Comment by hoyt-tian** [comment]
感谢提议，由于时间、精力限制，我将在年后对您的建议逐一评审并改进，issue将会保持open状态，直至全部问题处理完毕。

推荐使用 语雀 平台作为Gitbook替代品，详情请查看 https://yuque.com/

**Comment by Yurunsoft** [comment]
今天看到这个插件，感觉很不错，gitbook的编辑器太难用了，又卡问题又多。

这个插件如果能有目录编辑功能那真是太好了！

**Comment by hoyt-tian** [comment]
@simeng-li 

-  自动预览功能已经取消，vscode自带的预览已经非常便捷了，插件不再进行自动预览

- 插件单独占据一个activity bar项目，不再与资源浏览窗口中

- 目录编辑功能已经上线 @Yurunsoft

**Comment by Yurunsoft** [comment]
目录预览编辑的那个列表是不是应该用树形来展示，现在好多层级都在一起，有点乱的感觉
![image](https://user-images.githubusercontent.com/20104656/45331736-eb2f3580-b59e-11e8-8e84-0289ffde3809.png)

**Comment by hoyt-tian** [comment]
的确是树形展示。markdown里面多级缩紧需要以多个*或#显示，例如
\# \[一级标题\]()
\## \[二级标题\]()

注：树形栏目主要是为了方便操作章节目录，没有链接跳转到元素会被忽略，若要其可见，只需加上[]()包裹之即可。另外，右键菜单项中也可以操作目录树。

**Comment by Yurunsoft** [comment]
这样是否兼容gitbook呢，我图里就是gitbook编辑器生成出来的格式

**Comment by hoyt-tian** [comment]
👌我新开一个issue处理该功能

**Comment by hoyt-tian** [comment]
@Yurunsoft 版本更新至0.6.2，增加对缩紧排版的支持

**Comment by howmp** [comment]
@hoyt-tian 升级到0.6.1在之后，书的图标没有出现，一下是报错信息
```
[2018-09-11 10:14:11.271] [renderer1] [error] lilne is not defined: ReferenceError: lilne is not defined
    at lines.forEach.line (C:\Users\clevo\.vscode\extensions\hoyt-tian.gitbook-kit-0.6.1\src\outline.js:69:30)
    at Array.forEach (<anonymous>)
    at Function.from (C:\Users\clevo\.vscode\extensions\hoyt-tian.gitbook-kit-0.6.1\src\outline.js:24:11)
    at fs.readFile (C:\Users\clevo\.vscode\extensions\hoyt-tian.gitbook-kit-0.6.1\src\gitbook.js:128:32)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
版本信息

```
版本: 1.27.1 (user setup)
提交: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
日期: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
架构: x64
```

看起来`lilne`应该`line`

**Comment by hoyt-tian** [comment]
嗯，估计是键盘不小心碰到，插入了一个额外字符导致的，已经更新修复该问题。

**Comment by Yurunsoft** [comment]
太好了，今天把这个插件安利给了不少人~
