### ISSUE TITLE
Right clicking `Edit & Preview` says `SUMMARY.md` missing

### ISSUE THREAD

**Issue by DMXL** [hoyt-tian/vscode-gitbook-kit#5]
```
Can't find SUMMARY.md file in project root folder
```
The bug turns out to be unpredictable. Still trying to find the exact way to reproduce it.

Also the auto preview is very buggy... My suggestion is to turn it off completely because VSC has its own MD preview functionality by default.

**Comment by hoyt-tian** [comment]
Hi, thanks for your attention. Since I've no more time spare on this project, I suggest another better online doc https://www.yuque.com/yuque?language=en-us. Hope you may like it.
