### ISSUE TITLE
TypeError怎么解决？

### ISSUE THREAD

**Issue by yimikite** [hoyt-tian/vscode-gitbook-kit#6]
![image](https://user-images.githubusercontent.com/42052474/44130884-38c5e5f0-a082-11e8-8a63-18cec5f22b7f.png)
提示TypeError: Cannot read property 'type' of null，GITBOOK STRUCTURE中显示空白，没有内容，只有Example Code在右下角可以点开。

**Comment by hoyt-tian** [comment]
你好，由于本人精力有限，该项目已经停止维护，给您带来不便，非常抱歉，同时向您推荐一个在线文档服务，https://www.yuque.com/yuque，希望能满足您的需求

**Comment by hoyt-tian** [comment]
感谢关注，该问题已经在0.0.6版本中修复
